import { enable, disable, setFetchMethod } from "darkreader";
import { effective, siteFor, type Settings } from "./settings";
import { nativeDark } from "./detection";
// The Dark Reader API wraps sendMessage without forwarding its Promise result.
// Use Chrome's callback interface for reliable communication.
function send(message: unknown): Promise<any> {
  return new Promise((resolve, reject) =>
    chrome.runtime.sendMessage(message, (value) => {
      if (chrome.runtime.lastError)
        reject(Error(chrome.runtime.lastError.message));
      else if (value?.error) reject(Error(value.error));
      else resolve(value);
    }),
  );
}
setFetchMethod(async (url) => {
  const result = await send({ type: "fetch-css", url: String(url) });
  return new Response(result.text, { headers: { "Content-Type": "text/css" } });
});
let settings: Settings,
  host = "",
  available = false,
  active = false,
  status = "Disabled",
  timer: ReturnType<typeof setTimeout>,
  busy = false;
const observer = new MutationObserver((records) => {
  if (
    records.some((r) => {
      const e = r.target instanceof Element ? r.target : r.target.parentElement;
      return (
        !e?.closest(".darkreader") &&
        !(
          r.type === "childList" &&
          [...r.addedNodes, ...r.removedNodes].length &&
          [...r.addedNodes, ...r.removedNodes].every(
            (n) => n instanceof Element && n.classList.contains("darkreader"),
          )
        )
      );
    })
  )
    schedule();
});
function observe() {
  observer.observe(document, {
    subtree: true,
    childList: true,
    attributes: true,
    attributeFilter: [
      "class",
      "style",
      "data-theme",
      "data-color-mode",
      "href",
      "media",
    ],
  });
}
function apply() {
  if (busy || !settings) return;
  busy = true;
  observer.disconnect();
  try {
    // Measure the site's original colors, never the colors generated by Afterglow.
    if (active) {
      disable();
      active = false;
    }
    const native = nativeDark();
    if (!available) status = "Unavailable on this page";
    else if (!effective(settings, host)) status = "Disabled";
    else if (native && !siteFor(settings, host).force)
      status = "Native dark theme";
    else {
      enable(
        {
          darkSchemeBackgroundColor: "#181A1F",
          darkSchemeTextColor: "#E6E8ED",
          brightness: 100,
          contrast: 100,
          sepia: 0,
        },
        {
          ignoreImageAnalysis: ["*"],
          css: "a { color: #B9AEF5 !important; }",
          invert: [],
          ignoreInlineStyle: [],
          disableStyleSheetsProxy: true,
          ignoreCSSUrl: [],
        },
      );
      active = true;
      status = "Afterglow active";
    }
  } catch (error) {
    console.error("Afterglow theme failed", error);
    if (active) disable();
    active = false;
    status = "Unavailable on this page";
  } finally {
    busy = false;
    observe();
  }
}
function schedule() {
  clearTimeout(timer);
  timer = setTimeout(apply, 250);
}
async function refresh() {
  try {
    const c = await send({ type: "context" });
    if (c.error) throw Error(c.error);
    settings = c.settings;
    host = c.host;
    available = c.supported;
    schedule();
  } catch {
    status = "Unavailable on this page";
  }
}
chrome.storage.onChanged.addListener((_changes, area) => {
  if (area === "local") void refresh();
});
chrome.runtime.onMessage.addListener((m, _s, reply) => {
  if (m.type === "status") {
    reply({ status, host });
  }
  return false;
});
document.addEventListener("DOMContentLoaded", schedule, { once: true });
document.addEventListener("load", schedule, true);
matchMedia("(prefers-color-scheme: dark)").addEventListener("change", schedule);
observe();
void refresh();
